title: Claudio's Portfolio Website
baseURL: https://claudiosportfolio.netlify.app
languageCode: en-us
theme: gohugo-theme-ananke
resourceDir: ../resources
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: yes
languages:
  en:
    contentDir: content/en
    title: My portfolio 
    weight: 1
  de:
    contentDir: content/fr
    title: Mein portfolio
    weight: 2
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
params:
  author: ''
  background_color_class: bg-black
  description: The last theme you'll ever need. Maybe.
  facebook: ''
  favicon: ''
  featured_image: /Users/jack/Desktop/London Business School/Classes/CA09/XXXX/Background.jpeg
  github: ''
#  gitlab: ''
  # instagram: ''
 # linkedin: ''
#  mastodon: ''
  # recent_posts_number: 2
 # rss: ''
#  site_logo: ''
 # slack: ''
#  stackoverflow: ''
 # twitter: 
 # youtube: ''
