title: My Data Analytics Portfolio
baseURL: https://https://claudiosportfolio.netlify.app/
languageCode: en-us
theme: gohugo-theme-ananke
resourceDir: ../resources
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: yes
languages:
  en:
    contentDir: content/en
    title: My Data Analytics Portfolio
    weight: 1
  de:
    contentDir: content/de
    title: Mein Data Analytics Portfolio
    weight: 2
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
params:
  author: Claudio
  background_color_class: bg-blue
  description: This website was created to showcase an excerpt of my work done during my Data Analytics course at the London Busienss School
  facebook: ''
  gitlab: ''
  instagram: ''
  linkedin: ''
  mastodon: ''
  recent_posts_number: 2
  rss: ''
  site_logo: ''
  slack: ''
  stackoverflow: ''
  twitter: 
  youtube: ''
